# Discussion

We have (1) developed a reduced-complexity model and (2) compiled a spatially explicit time series data set of agricultural management data in order to (3) analyze the role of agricultural management in historical cropland SOC dynamics. Our study shows that information on agricultural management alters estimates of the SOC debt and slows down loss of SOC compared to the often used constant management assumptions. 

It is important to evaluate the validity of our results as modeling management effects on SOC dynamics at the global scale comes with large uncertainties. The model includes a large number of parameters, and for most of these the uncertainty distributions have not been quantified so far. Moreover, we think that beyond parameter uncertainty, the structural uncertainty from the model design is high. The management data itself is prone to uncertainties as well, as most of it is only indirectly calculated from reported data.

In the following, we give a qualitative assessment of the uncertainties and limitations of this study as well as discuss our three study objectives and results against existing literature.

## Comprehensive historical agricultural management data set

Our spatially explicit time series data set of agricultural management is based on country-specific FAO production and cropland statistics [@faostat_faostat_2016] as well as 0.5 degree land-use data from LUH2 [@hurtt_harmonization_2020]. Starting from these two sources, we derive a harmonized and consistent data set for the major C flows within the cropping system (\@ref(fig:FlowFig)) using a mass balance approach from the IPCC guidelines Vol. 4 [@eggleston_ipcc_2006; @calvo_buendia_ipcc_2019] and other auxiliary data sets [e.g. @porwollik_generating_2019].

For some of the aspects covered in our data set, for example livestock distribution [@robinson_mapping_2014] or manure production and application [@zhang_global_2017], well-compiled data sets in high resolution exist that capture real world conditions much better than our estimates. However, they often come with the caveats of either being static in time, demanding large sets of auxiliary data or being inconsistent with each other. 

For most of the parameters used in our management estimates no uncertainty estimates exist. This is why, in our view, a large part of the uncertainty with respect to the impacts of SOC management --- next to the parametric and structural uncertainty of the soil model --- is included in the management data itself. This is especially the case for the residue and manure production and application numbers, as these are only indirectly derived from crop and livestock production, feed and area data [@faostat_faostat_2016; @weindl_livestock_2017]. The uncertainty of recycling shares adds on top of the uncertain total numbers of manure and residue biomass. Previous modeling studies of SOC carbon on cropland often only used stylized scenarios of management practices [@pugh_simulated_2015; @lutz_simulating_2019], rather than trying to estimate real management. 

While our data set, by including crop residues and manure, likely the largest carbon inputs to soils, it does not account for a list of minor carbon inputs from cover crops, agroforestry, green manure, weed biomass as well as application of human excreta, sewage sludge, processing wastes, forestry residues or biochar. Including these sources would correct our estimates upwards and bring our estimates closer to the IPCC stock change factors (see Sect. \@ref(sec:ipcccompare)). Unfortunately, data on the quantity of these inputs is very scarce and does not exist with global coverage. 

SOC inputs from above-ground residues had the strongest management effect on SOC debt dynamics on cropland (see Fig. \@ref(fig:SOCscen)). As pointed out by Keel et al. [-@keel_large_2017] and Smith et al. [-@smith_how_2020], carbon input calculations are highly sensitive to the choice of allometric functions determining below- and above-ground residue estimates from harvested quantities (see \@ref(tab:c2dm) for coefficients used in this study). Keel et al. [-@keel_large_2017] question whether below-ground residues might increase with a fixed root:shoot ratio rather than being independent of productivity gains. Moreover, the study pointed out that plant breeding shifts allometries, which might not be reflected in outdated data sources. While our study considers a dynamic harvest index with rising yields for several crops, we may still overestimate residue biomass, in particular for below-ground biomass. 

## Reduced complexity SOC model

Our reduced-complexity SOC model is based on a Tier 2 modeling approach. This reduces the computational and data demand of the model in comparison to DGVMs, while still allowing for the explicit representation of agricultural management practices. Along with the effects of various C inputs, the impacts of water supply from rainfall and irrigation as well as tillage systems can also be accounted for in the computation of SOC decay rates. As such, the model can reflect the spatial and temporal heterogeneity in both management and biophysical conditions. 

The substantial impact of changing management practices through time is indicated by the development of our estimated stock change factors (see Fig. \@ref(fig:SCFglo)) as well as by the time trend of the SOC debt (see Fig. \@ref(fig:SOCmaps)(a)). Residue management has changed over the last decades, especially with the phasing out of residue burning practices in several regions and increased general productivity, showing a clear impact on SOC dynamics --- underlining the importance to account for these effects in soil carbon modeling. 

The Tier 2 approach [@ogle_cropland_in_ipcc_2019] used here is explicitly designed for agricultural soils, whereas we apply it also to soils under PNV. This is necessary in order to represent SOC losses under land-use change in a dynamic way, as this is an important driver of SOC dynamics. The comparison of simulated PNV data with LPJmL4 shows the model's capability in reproducing PNV SOC stocks (Fig. \@ref(fig:SOCLPJmL4)).
Concurrently, the point-data comparison (see Fig. \@ref(fig:SOCpoint)) shows low correlation for PNV, however also for cropland sites. This might also point to the fact that SOC stocks can vary at field and local scale considerably and thus a very high number of point data is needed to derive statistical properties that could improve the point-to-grid-cell comparison [see @rammig_generic_2018].f

Using litterfall estimates from LPJmL4, we have been able to estimate the total SOC stocks of the world, which is dominated by SOC under natural vegetation. However, as the world's SOC stock is highly uncertain, which is seen in the wide range of global SOC stock estimates for the first 30 cm of the soil profile [@batjes_harmonized_2016; @hengl_soilgrids250m_2017; @fao_global_2018; @schaphoff_lpjml4_2018-1; @poggio_soilgrids_2021; @sanderman_soil_2017] in Fig. \@ref(fig:SOCglo), the only conclusion we can draw from this is that our result is within a plausible range.

Additionally, we find our $0.2\,\unit{GtC\,yr^{-1}}$ SOC stock change within the period between 1975 and 2010 for the first 30 cm of the soil profile at the upper end of estimates comparing it to estimates of Ito et al. [-@ito_soil_2020] of $0.18\,\pm\,0.41\,\unit{GtC\,yr^{-1}}$ within the period between 1850 and 2014 for whole soil profile. This might be not surprising as the CO~2~ effect is most likely stronger and land-use change effects weaker within our later and shorter modeling period compared to a mean value of the period between 1850 and 2014.
The large uncertainty within estimates of SOC stock and its changes [@ito_soil_2020] again points to the large structural uncertainty within SOC modeling.

To avoid a strong impact of natural land representation and its uncertainties on our results, we focus on SOC changes on cropland. Pristine natural vegetated areas (like permafrost and rain forests) without human land management drop out in our calculation of SOC debt and stock change factors. Natural SOC estimates only influence results when natural land is converted to cropland. Moreover, the temporal dynamic of the SOC debt and stock change factors is not (or only to a small degree) altered by climatic or atmospheric effects on SOC stocks, as they cancel out by taking the difference (for the SOC debt) and ratio (for the stock change factors) of cropland SOC and SOC under hypothetical PNV conditions.

The initialization of SOC stocks, however, is important for the size of the SOC debt and its change over time, since the presence and size of legacy fluxes affect these values strongly (see Fig. \@ref(fig:SOCinit)). According to our sensitivity analysis the SOC debt varies between $33.3\,\unit{GtC}$ and $50.7\,\unit{GtC}$ depending on the initialization choice, with our best guess at $39.6\,\unit{GtC}$. Concurrently, our results indicate that the impact of the dynamic agricultural management is robust to the initialization of SOC stocks.

Comparing the geographic SOC patterns to Soil Grids 2.0 [@poggio_soilgrids_2021] (see Fig. \@ref(fig:SOCSoilGrids2Q)), we find that our model estimates values of SOC stocks greater than the estimated confidence intervals in Soil Grid 2.0 for some mountainous regions across the globe. This could indicate that we are not capable in capturing specific processes that would reduce the vegetation's productivity (such as erosion on steep slopes or shallow soils [@borrelli_assessment_2017]). A large swathe of eastern North America was heavily affected by the dust bowl event, with wind erosion removing large parts of the topsoils, a process not considered in our model. Similarly, we likely overestimate SOC stocks for the loess soils in northern China and the Altiplano in Latin America; in both cases erosion is a likely reason. In contrast, we estimate lower SOC stocks at the edges of the Sahara, where uncertain local water availability and artifical irrigation may dominate spatial SOC patterns.

In our model, erosion might however only affect the spatial pattern but not the aggregate SOC pool. As pointed out by Doetterl et al. [-@doetterl_erosion_2016], the final fate of leached or eroded carbon is uncertain and might even offset LUC emissions [@wang_human-induced_2017]. Concurrently, other studies have claimed erosion moves SOC into aquatic reservoirs [@zhang_simulating_2020] and thus changing total global terrestrial SOC stock.
Whereas for soil quality analysis SOC displacement might play an important role, in this budget approach focused especially on the SOC debt, displaced but not emitted SOC can be treated as SOC that remains on the cropland. Erosion and degradation impacts on yields and therefore on soil C inputs are captured by our method as we base them on FAO statistics of actual production. Yet the distribution of production below the country level - which we allocate proportional to LPJmL production potentials that do not reflect erosion feedback to yields - will overestimate yields and therefore biomass inputs to eroded soils.

In comparison with default stock change factors of the IPCC guidelines, our model estimates a stronger decline of SOC stocks (Fig. \@ref(fig:SCFglo)) for almost all regions. Tropical soils might suffer from low C input rates due to large yield gaps (Global Yield Gap and Water Productivity Atlas. Available URL: www.yieldgap.org (accessed on: 03/01/2022)) and high shares of residue removal and burning in lower-income countries [@smil_crop_1999; @williams_influence_1997; @jain_emission_2014]. Yet, even when comparing our estimates to the low-input stock change factors of the IPCC, our SOC loss is roughly twice as large as the revised 2019 IPCC default values [-@ogle_cropland_in_ipcc_2019], while it shows good agreement with the older default values from IPCC [-@lasco_cropland_in_ipcc_2006]. However, the revised estimates of the IPCC included much more and more recent data points, calling for a closer look on causes for the large deviations between our results and the refined Tier 1 factors. 
On the one hand, our approach does not account for unharvested carbon inputs from weeds or biomass cover on short-term fallows. Shifting agriculture with fallow periods might be prominent in tropical regions. While long-term fallow land (>4 years) is excluded from FAOSTAT as cropland, short-term fallow is not. Thus, our carbon inputs for these areas might be underestimated, leading to too low stock change factors.
On the other hand, older studies by Don et al. [-@don_impact_2011] estimated SOC losses for tropical soils of around 25% on average corresponding to a stock change factor of 0.75, but also reported a wide range of measured SOC changes from -80% to +58%. Fujisaki et al. [-@fujisaki_forest_2015] however found much lower loss rates of around 9%, attributing the difference to the different time period lengths since the conversion to cropland. As our results do not specifically account for cropland age and most of the cropland is older than 20 years (as assumed for the default IPCC Tier 1 stock change factors) our stock change factors have to be lower by definition following the steady-state assumption that cropland will continue to approach a new equilibrium. 
For the same reason, our estimates for temperate regions might be lower than both IPCC [-@lasco_cropland_in_ipcc_2006] and IPCC [-@ogle_cropland_in_ipcc_2019] default values.
With the production-increasing impact of irrigation and fertilization on carbon-poor dryland soils, SOC under cropland can also be higher than under PNV with stock change factors above 1 (see Fig. \@ref(fig:SOCmaps)(d)), but these areas are much smaller than where the stock change factors are well below unity. 

Generally, limiting the analysis to the first 30 cm of the soil profile follows the IPCC guidelines [@eggleston_ipcc_2006; @calvo_buendia_ipcc_2019] and assumes that most of the SOC dynamics happen in the topsoil. In this regard several aspects are strongly simplified within our approach. Firstly, distribution of carbon inputs into different soil layers are neglected and all carbon inputs are allocated to the topsoil. This particularly overestimates SOC stocks in the first 30 cm of soil below deeper rooting vegetation, which is certainly the case for most of the woody natural vegetated areas. Second, changes to the subsoil are neglected, which is most important for tillage effects. Other management practices might be more equally effecting top- and subsoil as they do not directly the relocates carbon vertically. As Powlson et al. [-@powlson_limited_2014] have shown, the subsoil can be make a large difference in evaluating total SOC losses or gains for no-tillage systems. No-tillage effects may seem larger than they actually are if only topsoil is considered. SOC transfers to deeper soil layers under tillage might enhance subsoil SOC compared to no-till practices. However, the effect of no-till to the subsoil as well as its overall importance as a SCS measure is still debated [@ogle_climate_2019]. Finally, organic soils (like peat- and wetlands) and drained cropland areas are not explicitly considered and emissions from these cropland areas are thus likely substantially underestimated. 

## SOC debt and SOC drivers

The analysis of SOC stock gains and losses is complex and has several dimensions as climatic and anthropogenic effects overlap. There is broad consensus that land conversion to cropland has caused substantial C emissions over the historical period [e.g. @frielingstein_glob_carbon_2020]. There is uncertainty with respect to the overall size of these emissions from different methods and reference points and with respect to the contribution of cropland and agricultural management to these emissions. In order to mitigate greenhouse gas emissions, it is essential to stop the decline of SOC stocks or even transform cropland management to sequester atmospheric C in cropland soils [@minasny_soil_2017]. Defining the SOC debt of 1975 as the baseline, and measuring land-use emissions on cropland as the difference between a potential natural state and the state under human interventions [see @pugh_simulated_2015], we find that global cropland has acted as a emissions source since 1975.
Comparing our SOC loss rate (the change of SOC debt) of $0.14\,\unit{GtC\,yr^{-1}}$ to estimates on land-use change induced emissions of $2.0\,\pm\,1.0\,\unit{GtC\,yr^{-1}}$ (sum of 'Bookkeeping LULCC emissions' and 'Loss of additional sink capacity' for the years 2009--2018 in Gasser et al. [-@gasser_historical_2020]), we find SOC emissions of the first 30 cm of the soil profile to be a minor contributor to overall land-use change induced emissions. 
Annual C loss rates of 0.2 per 1000 C still have the opposite trend as the promoted 4 per 1000 C sequestration rate target [@minasny_soil_2017]. Dedicated efforts to increase cropland SOC are thus necessary, as management improvements at historical rates are not enough to counteract ongoing SOC degradation on cropland. Yet our study also shows the substantial impact of changing management on the development of SOC debt (Fig. \@ref(fig:SOCdebt) and Fig. \@ref(fig:SOCscen)).

According to Sanderman et al. [-@sanderman_soil_2017], the SOC debt since the beginning of human cropping activities has been at around 37 GtC for the first 30 cm of the soil with half of it attributed to SOC depletion on grasslands. Our estimate of 39.6 GtC in 2010 for cropland debt is thus twice as high as their estimate. However, there are large uncertainties in modeling SOC at the global scale, and Sanderman et al. [-@sanderman_soil_2017] pointed out that their results might be conservatively low compared to experimental results. 

Furthermore, Sanderman et al. [-@sanderman_soil_2017] modeled historical trends based on agricultural land expansion without considering SOC variations due to time-variant agricultural management. Pugh et al. [-@pugh_simulated_2015] considered management effects like tillage and incorporation of residues in stylized and static scenarios only, so that they could not account for historical management effects on SOC dynamics. Their study moreover concludes that yield gains (by 18% in their simulations) do not lead to a substantial decline in SOC debt (less than 1% SOC increase). Historical yield increases, however, are estimated to be well above 50% [@pellegrini_crop_2018; @ray_recent_2012; @rudel_agricultural_2009] and often lead to an increase in below- and above-ground residue biomass inputs to the soil. While we find substantially larger SOC increase in response to productivity gains than the 1% reported by Pugh et al. [-@pugh_simulated_2015], this is not sufficient to compensate SOC losses from global cropland expansion of around 11% between 1974 and 2010.

The effects of agricultural productivity on cropland SOC dynamics, including historical yield trends and associated increases in residue inputs, can be directly accounted for in our modeling approach. In contrast, process-based studies [@pugh_simulated_2015; @herzfeld_soc_2021] often lack data on relevant management aspects that drive production increases. Herzfeld et al. [-@herzfeld_soc_2021] also consider historical management trends for fertilizer and manure inputs as well as on residue removal rates and tillage systems, but cannot reproduce the substantial increase in agricultural productivity over the last decades. Still, they find that compared to no-tillage systems, residue management has much larger potential to affect the strength of their projected future global cropland SOC decline. This is consistent with our finding that increasing SOC inputs from above-ground residues had the strongest effect on the slowing-down of the SOC debt increase (Fig. \@ref(fig:SOCscen)). In line with this, Dangal et al. [-@dangal_improving_2022] finds that no-tillage has only minor impacts on SOC dynamics across parts of the US.

Elliott et al. [-@elliott_management_trends_2018] show that yield trends in the USA can be reproduced by models, but require information on inputs that are not available at the global scale, such as annual data on sowing dates, planting densities, and genetic traits such as kernel number and radiation use efficiency. As such, it will remain challenging for process-based DGVMs to capture the trend of agricultural productivity on cropland SOC dynamics. 

Our study emphasizes again that the expansion of cropland is still a major source of CO~2~ emissions --- not only through the removal of vegetation, but also by a slow depletion of C stocks in soils. Our estimates indicate a SOC debt of 39.6 GtC in 2010, and every additional deforestated hectare adds to this debt. Avoided deforestation and other environmental regulation leads to intensification on existing cropland [@humpenoder_large-scale_2018] and our results show that such intensification could lead to increased cropland SOC, if residues are returned to the soil --- amplifying the C sequestration potential of avoided deforestation. 

There is also ample potential for further improved SOC management. As shown in Fig. \@ref(fig:FlowFig), the annual SOC respiration (1.3 GtC per year) is slightly above one quarter of total annual net C uptake by crops (4.6 GtC per year). C compounds have to be respired by soil organisms to maintain basic soil functions and regulate the nutrient cycle, which often leaves limited options to decrease C losses via SOC respiration [@janzen_soil_2006].
However, similar C losses occur at the end of the food supply chain (1.2 GtC per year), at the soil surface (1.5 GtC per year), and smaller but still considerable during residue burning (0.2 GtC per year) and within animal waste management systems (0.2 GtC per year). Improved management could include, firstly, a circular flow from the food supply chain back to soils. Waste composting or excreta recycling could represent a major additional C input to cropland soils [@brenzinger_organic_2018]. Secondly, soil carbon sequestration techniques [@smith_soil_2016], deep ploughing [@alcantara_deep_2016] or the transformation of C inputs to more recalcitrant biochar [@woolf_sustainable_2010] may transfer larger parts of the biomass at the litter soil barrier into permanent soil pools. Thirdly, reducing the share of residue burning and improved manure recycling could further increase C inputs. Finally, other carbon-accumulating practices, such as the cultivation of cover crops [@poeplau_carbon_2015; @porwollik_covercrops_2022] and agroforestry [@lorenz_soil_2014] could increase total C sequestration on cropland. 