---
title: "Global SOC maps and emissions"
output:
  md_document:
    variant: markdown_github
---

```{r load}
library(magclass)
library(madrat)
library(magpiesets)

rev <- "rev26"
setConfig(outputfolder = "/home/kristine/mnt/rd3mod/inputdata/output/")

filesNeeded <- c("SoilCarbon.rds","Landuse.rds")

scenarios    <- c("histManagement")#,"constManagement-1975", "constTillage-mixedtill", "constResidues-1975", "constManure-1975",
                  #"constManagement2-1975", "constResrate-1975", "constYield-1975",
                 #"Initial-natveg", "Initial-natveg_constManangement-1975", "Initial-natveg_constManangement2-1975", 
                 #"LitterPNV-PerennialGrasses", "LitterPNV-AASS", "LitterPNV-BRCF", 
                 #"LitterPNV-MTCF", "LitterPNV-BLEAF",  "LitterPNV-TREF")

# for(item in scenarios){
#    dir.create(path=paste0("Data/",paste0(rev,item)))
#    untar(paste0(getConfig("outputfolder"),"/", paste0(rev,item), "_h12_carbonbudget.tgz"),
#    files=filesNeeded, exdir=paste0("Data/", paste0(rev,item)), extras="--keep-newer-files ")
# }

outputdir <- "Output/Images"

SoilCarbon <- read.magpie(paste0("Data/",rev,scenarios[1],"/SoilCarbon.rds"))
Landuse    <- read.magpie(paste0("Data/",rev,scenarios[1],"/Landuse.rds"))

```

Calc global numbers

```{r Carbon Emissions (glo)}

library(reshape2)

years <- seq(1975,2010,1)

SoilCarbon[,,"naturalstate.crop"] <- SoilCarbon[,,"naturalstate.natveg"]
SOCStock        <- dimSums(dimSums(SoilCarbon[,years,][,,"state",pmatch=TRUE], dim=3.3)* Landuse[,years,], dim=3.2)
glo_SOCStock    <- dimSums(SOCStock, dim=1) 
glo_SOCEmission <- (glo_SOCStock[,,"naturalstate"] - glo_SOCStock[,,"actualstate"])/1000

cropland_dens    <- dimSums(SoilCarbon[,,"actualstate"][,,"crop"], dim=3)
cropland_dens[Landuse[,,"crop"]==0] <- NA

cropland_share <- dimSums(SoilCarbon[,,"actualstate"][,,"crop"], dim=3)/dimSums(SoilCarbon[,,"naturalstate"][,,"natveg"], dim=3)
cropland_share[Landuse[,,"crop"]==0] <- NA

cropland_increase <- dimSums(SoilCarbon[,,"actualstate"][,,"crop"], dim=3)-dimSums(SoilCarbon[,,"actualstate"][,,"natveg"], dim=3) 
cropland_increase[Landuse[,,"crop"]==0] <- NA

magpie_coord  <- toolGetMapping("magpie_coord.rda", type="cell")
share2plot    <- merge(as.data.frame(cropland_share), data.frame(magpie_coord, Cell=c(1:59199)), by="Cell")
increase2plot <- merge(as.data.frame(cropland_increase), data.frame(magpie_coord, Cell=c(1:59199)), by="Cell")
density2plot  <- merge(as.data.frame(cropland_dens), data.frame(magpie_coord, Cell=c(1:59199)), by="Cell")

```



```{r grid plot, out.height=800 , out.width=1200}

library(ggplot2)
theme_set(theme_bw())
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(sp)
library(rworldmap)
library(oce) 
library(scales)

legend_size <- 10

map.world <- map_data("world")
world         <- ne_countries(scale = "medium", returnclass = "sf")
data(coastlineWorld)  
coastline.world <- data.frame(longitude=coastlineWorld[["longitude"]],latitude=coastlineWorld[["latitude"]]) 

squish_trans <- function(from, to, factor) {
  
  trans <- function(x) {
    if (any(is.na(x))) return(x)
    # get indices for the relevant regions
    isq <- x > from & x < to
    ito <- x >= to
    # apply transformation
    x[isq] <- from + (x[isq] - from)/factor
    x[ito] <- from + (to - from)/factor + (x[ito] - to)
    return(x)
  }
  
  inv <- function(x) {
    if (any(is.na(x))) return(x)
    # get indices for the relevant regions
    isq <- x > from & x < from + (to - from)/factor
    ito <- x >= from + (to - from)/factor
    # apply transformation
    x[isq] <- from + (x[isq] - from) * factor
    x[ito] <- to + (x[ito] - (from + (to - from)/factor))
    return(x)
  }
  # return the transformation
  return(trans_new("squished", trans, inv))
}

SOCemis <- ggplot() + geom_line(data= as.data.frame(-glo_SOCEmission)[,c(3,6)],  aes(x = Year, y = Value, group=1)) +
  labs( x = "Year", 
        y = expression(paste('Global \u0394SOC in GtC'))) +
  scale_x_discrete(breaks=seq(1975,2010,5)) +
  scale_y_continuous(trans = squish_trans(-32,0,10),
                     limits = c(-38,0),
                     breaks = c(0, -32, -33, -34, -35, -36, -37, -38),
                     minor_breaks = seq(-1,-29,-2)) +
  theme(rect=element_blank(),
        axis.title.y= element_text(size=legend_size),
        axis.title.x= element_text(size=legend_size, margin = margin(t = 10, r = 0, b = 10, l = 0, unit = "pt")),
        axis.text.x = element_text(angle=60, hjust=0.8, vjust=0.8, size=legend_size)#,
        #plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
        ) +
  annotate(geom="text", label="SOC debt", x=factor(1995), y=-20, size = 3) +
  annotate("segment", x = factor(1990), xend = factor(1990), y = 0, yend = -34, arrow=arrow(end="both", type="closed", length=unit(0.1, "inches")))
 

cols          <- colorRampPalette(brewer.pal(11, "RdYlBu"))(7)

SOCshare <- ggplot(data = world) + geom_sf() + 
    geom_tile(data = subset(share2plot, Year=="2010", c("lon","lat","Value")), aes(x = lon, y = lat, fill = Value)) +
    scale_fill_stepsn(limits=c(0,2), colours = cols, 
                      name = expression("cropland SOC stock change factor (unitless)"), 
                      breaks=c(0.3,0.6,0.9,1.1,1.4,1.7,2),
                      labels=c("0     0.3","  0.6", "  0.9","  1.1","  1.4","  1.7","> 2"), na.value = "white",
                      guide = guide_legend(
                        title.theme=element_text(size=legend_size),
                        direction = "horizontal",
                        title.position = 'top',
                        # I shift the labels around, the should be placed 
                        # exactly at the right end of each legend key
                        title.hjust = 0.5,
                        label.hjust = 1,
                        nrow = 1,
                        byrow = F,
                        label.position = "bottom",
                        keyheight = 0.5,
                        keywidth  = 2
                      )) +
    theme(legend.position="bottom",
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          legend.text=element_text(size=legend_size),
          rect=element_blank(),
          panel.background=element_rect(fill="#F8F8FF", size=c(0.7,0.7)),
          plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
          )  

#geom_map(dat=map.world, map = map.world, aes(map_id=region), fill="NA", color="black") +

SOCincrease <- ggplot(data = world) + geom_sf() +
    geom_tile(data = subset(increase2plot, Year=="2010", c("lon","lat","Value")), aes(x = lon, y = lat, fill = Value)) +
    scale_fill_stepsn(limits=c(-100,100), colours = cols, 
                      name = expression(paste('cropland \u0394SOC in tons of carbon per hectare')), 
                      values=(c(-100,-50,-20,-10,10,20,50,100)+100)/200,
                      breaks=c(-50,-20,-10,10,20,50,100),
                      labels=c("< -100    -50", "  -20","  -10","  10","  20","  50"," > 100"), na.value = "white",
                      guide = guide_legend(
                        title.theme=element_text(size=legend_size),
                        direction = "horizontal",
                        title.position = 'top',
                        # I shift the labels around, the should be placed 
                        # exactly at the right end of each legend key
                        title.hjust = 0.5,
                        label.hjust = 1,
                        nrow = 1,
                        byrow = F,
                        label.position = "bottom",
                        keyheight = 0.5,
                        keywidth  = 2
                      )) +
    theme(legend.position="bottom",
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          legend.text=element_text(size=legend_size),
          rect=element_blank(),
          panel.background=element_rect(fill="#F8F8FF", size=c(0.7,0.7)),
          plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
          )

cols <- colorRampPalette(brewer.pal(9, "YlGn"))(8)[2:8]

SOCdensity <- ggplot(data = world) + geom_sf() +
    geom_tile(data = subset(density2plot, Year=="2010", c("lon","lat","Value")), aes(x = lon, y = lat, fill = Value)) +
    scale_fill_stepsn(limits=c(0,150), colours = cols, 
                      name = expression("cropland SOC in tons of carbon per hectare"), 
                      values=c(0,5,10,20,40,70,100,150)/150,
                      breaks=c(5,10,20,40,70,100,150),
                      labels=c("0     5","  10","  20","  40","  70","  100"," >150"), na.value = "white",
                      guide = guide_legend(
                        title.theme=element_text(size=legend_size),
                        direction = "horizontal",
                        title.position = 'top',
                        # I shift the labels around, the should be placed 
                        # exactly at the right end of each legend key
                        title.hjust = 0.5,
                        label.hjust = 1,
                        nrow = 1,
                        byrow = F,
                        label.position = "bottom",
                        keyheight = 0.5,
                        keywidth  = 2
                      )) +
    theme(legend.position="bottom",
          axis.title.x = element_blank(), 
          axis.title.y = element_blank(),
          legend.text=element_text(size=legend_size),
          rect=element_blank(),
          panel.background=element_rect(fill="#F8F8FF", size=c(0.7,0.7)),
          plot.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
          )



library(gridExtra)
library(cowplot)
SOCdensity
SOCincrease
SOCemis
SOCshare

grid <- plot_grid(SOCdensity,SOCincrease, SOCshare, SOCemis,  ncol=2, labels=c("(a)","(b)", "(c)", "(d)"),
                  label_fontface = "plain", label_size = 10)
grid
ggsave(paste0(outputdir,"/4panelfigure.png"), plot=grid, width = 20, height = 14, dpi = 300, units = "cm")
ggsave(paste0(outputdir,"/SOCshare.png"),    plot=SOCshare,    width = 10, height = 7, dpi = 300, units = "cm")
ggsave(paste0(outputdir,"/SOCincrease.png"), plot=SOCincrease, width = 10, height = 7, dpi = 300, units = "cm")
ggsave(paste0(outputdir,"/SOCdensity.png"),  plot=SOCdensity,  width = 10, height = 7, dpi = 300, units = "cm")
ggsave(paste0(outputdir,"/SOCemis.png"),     plot=SOCemis,     width = 10, height = 7, dpi = 300, units = "cm")

```








