---
title: "SOC budget analysis in comparsion"
output:
  html_document:
    df_print: paged
  pdf_document: default
  bookdown::pdf_document2: default
   keep_md: true
---

```{r load}
library(magclass)
library(madrat)
library(mrcommons)

outputdir <- "Output/Images/"

rev         <- "rev30"

SoilCarbon <- readRDS(paste0("Data/", rev, "histManagement/SoilCarbon.rds"))
Landuse    <- readRDS(paste0("Data/", rev, "histManagement/Landuse.rds"))

```


Calculate global carbon stocks

```{r Carbon Stock (cell iso reg glo)}

cropland        <- Landuse[,,"crop"]
SOCStock_natveg <- dimSums(SoilCarbon[,,c("naturalstate.natveg")], dim=3)
SOCStock_lu     <- dimSums(SoilCarbon[,,c("actualstate")]*Landuse, dim=3)/dimSums(Landuse, dim=3)

SOCStock_natveg[cropland <= 0.001] <- NA
SOCStock_lu[    cropland <= 0.001] <- NA


```


```{r load soc validation stocks}

  # SoilGrids2
  SoilGrids2       <- readRDS(paste0("Data/", rev, "histManagement/SoilGrids2_grid.rds"))
  SoilGrids2_full  <- mbind(setNames(SoilGrids2,     "SOC"),
                            setNames(readRDS(paste0("Data/", rev, "histManagement/SoilGrids2_Q0p95.rds")), "SOC_Q95"),
                            setNames(readRDS(paste0("Data/", rev, "histManagement/SoilGrids2_Q0p05.rds")), "SOC_Q05"))
  
  #LPJmL4
  LPJmL4_CRU <- toolCoord2Isocell(readRDS(paste0("Data/", rev, "histManagement/LPJmL4_CRU.rds")))
  LPJmL4_CRU <- LPJmL4_CRU[,getYears(Landuse),]

  LPJmL4_CRU[cropland            <= 0.001] <- NA
  SoilGrids2[cropland[,"y2010",] <= 0.001] <- NA
  SoilGrids2_full[cropland[,"y2010",] <= 0.001] <- NA
  
```





```{r correation plot CRU, fig.height=6, fig.width=6}

climate   <- read.csv("Data/additional/ClimateZoneMapping.csv")
climate$N <- as.integer(substring(climate$cell, 5))
climate   <- climate[order(climate$N), ]
climates  <- unique(climate$IPCC_reduced)

layout(matrix(c(1, 2, 3, 4), ncol = 2, byrow = TRUE), 
       heights = c(0.48, 0.52), widths =  c(0.52, 0.48))

xlabel <- c("", "", "LPJmL4 (t/ha) in 2010", "LPJmL4 (t/ha) in 2010")
ylabel <- c("This Study - PNV (t/ha) in 2010", "", "This Study - PNV (t/ha) in 2010", "")

layout.show(n = 4)

mar <- list(c(2, 4, 1, 1),
            c(2, 2, 1, 1),
            c(4, 4, 1, 1),
            c(4, 2, 1, 1))

years <- "y2010"

for (i in 1:length(climates)) {
  
  icells <- as.array(climate$cell[climate$IPCC_reduced == climates[i]])
  par(mar = mar[[i]])
  max <- max(    LPJmL4_CRU[icells, years, ], SOCStock_natveg[icells, years, ], na.rm = TRUE)
  min <- c(10, 20, 10, 20)
  
  plot(LPJmL4_CRU[icells, years, ], SOCStock_natveg[icells, years, ], asp = 1, 
       xlab = xlabel[i], ylab = ylabel[i],
       col = "white", pch = ".", log = "xy",
       xlim = c(min[i], max), ylim = c(min[i], max))
  
  points(LPJmL4_CRU[icells ,years ,],SOCStock_natveg[icells, years, ], pch = ".")
 
  lines(c(min[i], max), c(min[i], max), col = "grey")
  
  text(min[i], max, paste0("R2=", round(cor(LPJmL4_CRU[icells, years, ],SOCStock_natveg[icells, years, ], 
                                 use = "complete.obs"), 2)), adj = c(0,1))
  text(max, min[i], paste0("Climate zone: ", gsub("_", " ", climates[i])), adj = c(1, 0))
}

dev.copy(png, paste0(outputdir, "scatterCompareLPJmL42010_pnv.png"), width = 1500, height = 1500, res = 250)
dev.off()

print(round(cor(LPJmL4_CRU[, years, ],SOCStock_natveg[, years, ], use = "complete.obs"), 2))


```

```{r correation plot SoilGrids2, fig.height=6, fig.width=6}

climate   <- read.csv("Data/additional/ClimateZoneMapping.csv")
climate$N <- as.integer(substring(climate$cell, 5))
climate   <- climate[order(climate$N),]
climates  <- unique(climate$IPCC_reduced)

layout(matrix(c(1, 2, 3, 4), ncol = 2, byrow = TRUE), 
       heights = c(0.48, 0.52), widths =  c(0.52, 0.48))

xlabel <- c("", "", "SoilGrids2 (t/ha)", "SoilGrids2 (t/ha)")
ylabel <- c("This Study (t/ha)", "", "This Study (t/ha)", "")

layout.show(n = 4)

mar <- list(c(2, 4, 1, 1),
            c(2, 2, 1, 1),
            c(4, 4, 1, 1),
            c(4, 2, 1, 1))

years <- "y2010"

for (i in 1:length(climates)) {
  
  icells <- as.array(climate$cell[climate$IPCC_reduced == climates[i]])
  par(mar = mar[[i]])
  max <- max(    SoilGrids2[icells ,years, ], SOCStock_lu[icells, years, ], na.rm = TRUE)
  min <- c(5, 10, 5, 10)
  
  plot(SoilGrids2[icells, years, ],SOCStock_lu[icells, years, ], asp = 1, 
       xlab = xlabel[i], ylab = ylabel[i],
       col = "white", pch = ".", log = "xy",
       xlim = c(min[i], max), ylim = c(min[i], max))
  
  points(SoilGrids2[icells, years, ],SOCStock_lu[icells, years, ], pch = ".")
 
  lines(c(min[i], max), c(min[i], max), col = "grey")
  
  text(min[i], max, paste0("R2=", round(cor(SoilGrids2[icells, years, ], SOCStock_lu[icells, years, ], 
                                 use = "complete.obs"), 2)), adj = c(0,1))
  text(max, min[i], paste0("Climate zone: ", gsub("_", " ", climates[i])), adj = c(1, 0))
}

dev.copy(png, paste0(outputdir, "scatterCompareSoilGrids2_2010_lu.png"), width = 1500, height = 1500, res = 250)
dev.off()

print(round(cor(SoilGrids2[, years, ],SOCStock_lu[, years, ], use = "complete.obs"), 2))

```


```{r quantileSOILGRIDS2, fig.height=6, fig.width=12}

InOrOut <- SOCStock_lu[,"y2010",]
InOrOut[] <- NA
InOrOut[SOCStock_lu[,"y2010",] > SoilGrids2_full[,"y2010","SOC_Q05"] & 
        SOCStock_lu[,"y2010",] < SoilGrids2_full[,"y2010","SOC_Q95"]] <- 1
InOrOut[SOCStock_lu[,"y2010",] < SoilGrids2_full[,"y2010","SOC_Q05"]] <- 0.5
InOrOut[SOCStock_lu[,"y2010",] > SoilGrids2_full[,"y2010","SOC_Q95"]] <- 1.5

magpie_coord      <- toolGetMapping("magpie_coord.rda", type="cell")
soilgrid22plot    <- merge(as.data.frame(InOrOut), data.frame(magpie_coord, Cell=c(1:59199)), by="Cell")

```

```{r plot quantileSOILGRIDS2, fig.height=6, fig.width=12}

library(ggplot2)
theme_set(theme_bw())
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(sp)
library(rworldmap)
library(oce) 
library(scales)

legend_size <- 10

map.world <- map_data("world")
world         <- ne_countries(scale = "medium", returnclass = "sf")
data(coastlineWorld)  
coastline.world <- data.frame(longitude=coastlineWorld[["longitude"]],latitude=coastlineWorld[["latitude"]]) 

SOCplotmap   <- function(data, name, cols, limits, values = NULL, breaks, labels) {
  
  out <- ggplot(data = world) + geom_sf() + 
    geom_tile(data = subset(data, Year == "2010", c("lon","lat","Value")), aes(x = lon, y = lat, fill = factor(Value))) +
    scale_fill_manual(name     = name,
                      values   = cols,
                      labels   = labels, 
                      na.value = "white",
                      guide    = guide_legend(
                        title.theme    = element_text(size=legend_size),
                        direction      = "horizontal",
                        title.position = 'top',
                        # I shift the labels around, the should be placed 
                        # exactly at the right end of each legend key
                        title.hjust    = 0.5,
                        label.hjust    = 1,
                        nrow           = 1,
                        byrow          = F,
                        label.position = "bottom",
                        keyheight      = 0.5,
                        keywidth       = 2
                      )) +
    theme(legend.position = "bottom",
          axis.title.x     = element_blank(), 
          axis.title.y     = element_blank(),
          legend.text      = element_text(size = legend_size),
          rect             = element_blank(),
          panel.background = element_rect(fill = "#F8F8FF", size = c(0.7,0.7)),
          plot.margin      = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")
          )  
  
    return(out)
}

cols              <- c("#648FFF", "#DC267F", "#FFB000")[c(1, 3, 2)]
SoilGrids2InMap   <- SOCplotmap( data     =  soilgrid22plot,
                                 limits   = c(0.5, 1.5),
                                 cols     = cols,
                                 name     = expression("Modeled SOC stock in relation to uncertainty range of SoilGrids 2.0"),
                            breaks   = c(0.5, 1.0, 1.5),
                            labels   = c("lower than Q0.05", "inside [Q0.05, Q0.95] ", "higher than Q0.95", "No Cropland"))

SoilGrids2InMap
ggsave(paste0(outputdir, "/SOCquantilesSoilGrids2.png"),    plot=SoilGrids2InMap,    width = 15, height = 10, dpi = 300, units = "cm")

```



