---
title: "First SOC budget analysis"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r load data}
library(mrcommons)
library(mrvalidation)
library(mrSOCbudget)

#setConfig(cachefolder = "/home/kristine/WORK/R libraries/rd3mod_inputdata/cache/rev4.43_SOC_0.5.0/", forcecache = TRUE)
setConfig(cachefolder = "/home/kristine/mnt/rd3mod/inputdata/cache/rev4.43_mrSOC_0.4.1/", forcecache = TRUE)
#setConfig(cachefolder = "/home/kristine/mnt/rd3mod/inputdata/cache/rev4.43/", forcecache = TRUE)
#setConfig(cachefolder = "/home/kristine/mnt/rd3mod/inputdata/cache/rev4.43/", forcecache = TRUE)
setConfig(sourcefolder = "/home/kristine/mnt/rd3mod/inputdata/sources/")
#setConfig(sourcefolder = "/home/kristine/WORK/R libraries/rd3mod_inputdata/sources/")

#SoilCarbon <- readRDS("/home/kristine/WORK/Paper/historicalsocbudget/ResultNotebooks/soilcarbon.rds")
SoilCarbon <- calcOutput("SoilCarbon", output="full", aggregate = FALSE)
Landuse    <- calcOutput("Landuse",      aggregate=FALSE)

```

Calculate global carbon stocks

```{r Carbon Stock (cell iso reg glo)}

SOCStock     <- dimSums(dimSums(SoilCarbon[,,"actualstate"], dim=3.3)* Landuse, dim=3)
glo_SOCStock <- dimSums(SOCStock, dim=1) 
cell2iso     <- toolGetMapping("CountryToCellMapping.csv", type = "cell")
iso_SOCStock <- toolCountryFill(toolAggregate(SOCStock, rel=cell2iso, from="celliso", to="iso", dim=1), fill=0)
iso2reg      <- toolMappingFile("regional",getConfig("regionmapping"),readcsv = TRUE)
reg_SOCStock <- toolAggregate(iso_SOCStock, rel=iso2reg, from="CountryCode", to="RegionCode")

print(mbind(dimSums(dimSums(SoilCarbon[,,"actualstate"], dim=3.3)* Landuse, dim=c(1,3)),
            dimSums(dimSums(SoilCarbon[,,"steadystate"], dim=3.3)* Landuse, dim=c(1,3))))

```

```{r Carbon loss}
SOCStock     <- dimSums(dimSums(SoilCarbon, dim=3.2)* Landuse[,,"crop"], dim=c(1,3.3))

SOCDiff      <- SOCStock[,,"crop"] - SOCStock[,,"natveg"]

plot(SOCDiff)

```


Load validation data:

```{r Validation Stocks}

  LPJ_IPCC   <- calcOutput("ValidCarbonStocks", datasource = "LPJ_IPCC2006", aggregate="REG+GLO", try=TRUE)
  LPJ_rev21  <- calcOutput("ValidCarbonStocks", datasource = "LPJmL_rev21", aggregate="REG+GLO", try=TRUE)
  LPJ_car    <- calcOutput("ValidCarbonStocks", datasource = "LPJmLCarbon", aggregate="REG+GLO", try=TRUE)
  WISE       <- calcOutput("ValidCarbonStocks", datasource = "WISE", aggregate="REG+GLO", try=TRUE)
  GSOC       <- calcOutput("ValidCarbonStocks", datasource = "GSOC", aggregate="REG+GLO", try=TRUE)
  SoilGrids  <- calcOutput("ValidCarbonStocks", datasource = "SoilGrids", aggregate="REG+GLO", try=TRUE)
  
```

Plot global stocks

```{r plot glo stocks}

plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red", xlim=c(1951,2017),  ylim=c(400000,1300000))
lines(getYears(LPJ_IPCC, as.integer = TRUE), LPJ_IPCC["GLO",,1], type="l", col="green")
lines(getYears(LPJ_car, as.integer = TRUE), LPJ_car["GLO",,], type="l", col="darkgreen")
lines(getYears(LPJ_rev21, as.integer = TRUE), LPJ_rev21["GLO",,2], type="l", col="lightgreen")
lines(getYears(WISE, as.integer = TRUE), WISE["GLO",,], type="l", col="brown")
lines(getYears(SoilGrids, as.integer = TRUE), SoilGrids["GLO",,], type="l", col="blue")
lines(getYears(GSOC, as.integer = TRUE), GSOC["GLO",,], type="l", col="pink")
plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red")
```



Plot regional stocks

```{r plot reg stock, out.width="100%", out.height=1000}

library(mip)
library(quitte)
library(ggplot2)

getNames(reg_SOCStock) <- paste0("modeloutput.SOCbudget.", getNames(WISE,dim=3))
getSets(reg_SOCStock)  <- getSets(WISE) 

hist <- rbind(as.quitte(WISE["GLO",,,invert=TRUE]),
              as.quitte(GSOC["GLO",,,invert=TRUE]),
              as.quitte(SoilGrids["GLO",,,invert=TRUE]),
              as.quitte(LPJ_rev21["GLO",,,invert=TRUE][,,2]))

mipLineHistorical(reg_SOCStock, hist, facet.ncol=4, scales="free_y", ylab="SOC (0-30cm) in MtC")

print(dimSums(reg_SOCStock, dim=1))
```


```{r barplot reg stock, out.width="100%", out.height=1000}

library(mip)
library(quitte)
library(ggplot2)


getNames(reg_SOCStock) <- paste0("modeloutput.SOCbudget.", getNames(WISE,dim=3))
getSets(reg_SOCStock)  <- getSets(WISE) 
year <- "y2010"

all <- rbind( as.quitte(reg_SOCStock[,year,]),
              as.quitte(WISE["GLO",,,invert=TRUE][,1,]),
              as.quitte(GSOC["GLO",,,invert=TRUE][,1,]),
              as.quitte(SoilGrids["GLO",,,invert=TRUE][,1,]),
              as.quitte(LPJ_IPCC["GLO",,,invert=TRUE][,,1][,year,]),
              as.quitte(LPJ_car["GLO",,,invert=TRUE][,year,]),
              as.quitte(LPJ_rev21["GLO",,,invert=TRUE][,,2][,year,]))
all$scenario <- all$model
all$model    <- "HistSOC"



mipBarYearData(reg_SOCStock)
```
Plot global stocks

```{r plot glo stocks}

plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red", xlim=c(1951,2017),  ylim=c(400000,1300000))
lines(getYears(LPJ_IPCC, as.integer = TRUE), LPJ_IPCC["GLO",,1], type="l", col="green")
lines(getYears(LPJ_car, as.integer = TRUE), LPJ_car["GLO",,], type="l", col="darkgreen")
lines(getYears(LPJ_rev21, as.integer = TRUE), LPJ_rev21["GLO",,2], type="l", col="lightgreen")
lines(getYears(WISE, as.integer = TRUE), WISE["GLO",,], type="l", col="brown")
lines(getYears(SoilGrids, as.integer = TRUE), SoilGrids["GLO",,], type="l", col="blue")
lines(getYears(GSOC, as.integer = TRUE), GSOC["GLO",,], type="l", col="pink")
plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red")
```



Plot cellular stocks

```{r plot reg stock, out.width="100%", out.height=1000}

library(luplot)
library(magpiesets)


cellSOCdens   <- (dimSums(dimSums(SoilCarbon[,,"naturalstate"], dim=3.2) * Landuse, dim=c(3))/dimSums(Landuse, dim=c(3)))[,findset("past"),]
cellSOCdens[is.na(cellSOCdens)] <- 0

cellSoilGrids <- readSource("SoilGrids", subtype="cstock_0_30", convert="onlycorrect")
cellLPJml     <- calcOutput("LPJmL", version="LPJmL4", climatetype="CRU_4", subtype="soilc_layer", time="raw", selectyears="past", aggregate=FALSE)
cellLPJml     <- collapseNames(cellLPJml[,,"layer1"]+1/3*cellLPJml[,,"layer2"], collapsedim = c(2,3))



diffSoilGrids <- cellSOCdens - cellSoilGrids
diffLPJml     <- cellSOCdens - cellLPJml

luplot::plotmap(diffLPJml[,10,], legend_range = c(-80,80))
```




```{r table dens climatezones}
    
    library(magpiesets)

    koeppen     <- readSource("Koeppen", subtype="cellular", convert="onlycorrect" )
    getNames(koeppen) <- tolower(getNames(koeppen))
    koepp2IPCC  <- toolGetMapping("mapping_koeppen_ipcc.csv", type = "sectoral")
    koepp2IPCC$koeppen_geiger <- tolower(koepp2IPCC$koeppen_geiger)
    climateIPCC <- toolAggregate(koeppen, rel=koepp2IPCC, from="koeppen_geiger", to="ipcc_reduced", dim=3)
    climateIPCC <- climateIPCC[,getYears(SoilCarbon),]
  
    SOCDens_lut <- dimSums(SoilCarbon[,,c("steadystate","actualstate","naturalstate")], dim=3.3) 
    SOCDens_lut[,,"naturalstate.crop"] <- SOCDens_lut[,,"actualstate.crop"]
    
    SoilCshare_ipcczone2 <- dimSums(climateIPCC * SOCDens_lut[,,"crop"] * Landuse[,,"crop"], dim=1)/
                            dimSums(climateIPCC * SOCDens_lut[,,"natveg"] * Landuse[,,"crop"], dim=1)
    
    print(collapseNames(SoilCshare_ipcczone2[,findset("past"),]))
    
    
```



```{r plot density maps}


cropland_share <- dimSums(SoilCarbon[,,"actualstate"][,,"crop"], dim=3)/dimSums(SoilCarbon[,,"naturalstate"][,,"natveg"], dim=3)
cropland_share[Landuse[,,"crop"]==0] <- NA

cropland_increase <- dimSums(SoilCarbon[,,"actualstate"][,,"crop"], dim=3)-dimSums(SoilCarbon[,,"actualstate"][,,"natveg"], dim=3) 
cropland_increase[Landuse[,,"crop"]==0] <- NA

library(RColorBrewer)
cols      <- colorRampPalette(brewer.pal(11, "RdYlGn"))(7)[]
outputdir <- "/home/kristine/WORK/Paper/historicalsocbudget/SOCbudgetPaper/images/maps/"

png(paste0(outputdir,"CShare_1965.png"),width = 1280, height = 720, res = 108)
luplot::plotmap(cropland_share[,"y1965",], legend_range = c(0,2), legend_colours = cols, main="C_share on Cropland 1965")
dev.off()
png(paste0(outputdir,"CShare_2010.png"),width = 1280, height = 720, res = 108)
luplot::plotmap(cropland_share[,"y2010",], legend_range = c(0,2), legend_colours = cols, main="Stock Change Factor on Cropland 2010")
dev.off()

png(paste0(outputdir,"CIncrease_1965.png"),width = 1280, height = 720, res = 108)
luplot::plotmap(cropland_increase[,"y1965",], legend_range = c(-80,80), legend_colours = cols, main="Absoulte C change on Cropland 1965")
dev.off()

png(paste0(outputdir,"CIncrease_2010.png"),width = 1280, height = 720, res = 108)
luplot::plotmap(cropland_increase[,"y2010",], legend_range = c(-80,80), legend_colours = cols, main="Absoulte C change on Cropland 2010")
dev.off()


library(RColorBrewer)
pal_red    <- c("#110044","#774499","#FF0088","#FFAADD")
pal_green  <- c("#004400","#00FF00","#FFFF00","#FFFFCC")
pal_blue   <- c("#000044","#0000FF","#00FFFF","#CCFFFF")
pal_yellow <- c("#FFDD99","#feb24c","#FF0000","#440000")

pal_red    <- c("#FFAAAA","#AAFFFF")
pal_green  <- c("#AAFFAA","#FFAAFF")
pal_blue   <- c("#AAAAFF","#FFFFAA")
pal_grey   <- c("#AAAAAA","#222222")


cols <- c(colorRampPalette(pal_red)(500)[500:1],
          colorRampPalette(pal_yellow)(500),
          colorRampPalette(pal_blue)(500)[500:1],
          colorRampPalette(pal_green)(500)[500:1]
          )


test <- cropland_share
test[Landuse[,,"crop"]==0] <- NA
test[test>2]  <- 1.9999
test[test==0] <- 0.0001

koeppen     <- readSource("Koeppen", subtype="cellular", convert="onlycorrect" )
getNames(koeppen) <- tolower(getNames(koeppen))
koepp2IPCC  <- toolGetMapping("mapping_koeppen_ipcc.csv", type = "sectoral")
koepp2IPCC$koeppen_geiger <- tolower(koepp2IPCC$koeppen_geiger)
climateIPCC <- toolAggregate(koeppen, rel=koepp2IPCC, from="koeppen_geiger", to="ipcc_reduced", dim=3)
climateIPCC <- climateIPCC[,getYears(SoilCarbon),]

test <- test*climateIPCC[,,1]+(test+2)*climateIPCC[,,2]+(test+4)*climateIPCC[,,3]+(test+6)*climateIPCC[,,4]
luplot::plotmap(test[,"y2010",], legend_range = c(0,8), legend_colours = cols)

outputdir <- "/home/kristine/WORK/Paper/historicalsocbudget/SOCbudgetPaper/images/maps/"
png(paste0(outputdir,"CShare_4ColorClimates.png"),width = 1280, height = 720, res = 108)
luplot::plotmap(test[,"y2010",], legend_range = c(0,8), legend_colours = cols, main="Stock Change Factor on Cropland 2010 (climate zones color coded)")
dev.off()


```


```{r plot density maps}


cols <- colorRampPalette(brewer.pal(9,"Oranges"))(1000)
cropland <- dimSums(SoilCarbon[,,"crop"], dim=3)
cropland[Landuse[,,"crop"]==0] <- NA

luplot::plotmap(cropland[,"y2010",], legend_colours = cols, legend_range=range(cropland[,"y2010",]/5, na.rm=TRUE))

natland <- dimSums(SoilCarbon[,,"natveg"], dim=3)

luplot::plotmap(natland[,"y2010",], legend_colours = cols, legend_range=range(cropland[,"y2010",]/5, na.rm=TRUE))

```

```{r output carbon flows}


```