---
title: "Global SOC maps and emissions"
output:
  md_document:
    variant: markdown_github
  html_document:  
---

```{r load}
library(mrcommons)
library(mrvalidation)
library(mrSOCbudget)
library(magpiesets)

rev       <- c(Default="rev0.71default", Till="rev0.72default", HiHi="rev0.71LGhigh_Nhigh", HiLo="rev0.71LGhigh_Nlow", LoHi="rev0.71LGlow_Nhigh", LoLo="rev0.71LGlow_Nlow")
outputdir <- "Output/Images"

```

Calc global numbers

```{r Carbon Emissions (glo)}

library(ggplot2)

col <- c("black","red","green","blue","brown","pink")

range        <- NULL
litter_param <- NULL

for(r in 1:length(rev)){
  SoilCarbon <- read.magpie(paste0("Data/",names(rev[r]),"/SoilCarbon.rds"))
  Landuse    <- read.magpie(paste0("Data/",names(rev[r]),"/Landuse.rds"))
  SoilCarbon[,,"naturalstate.crop"] <- SoilCarbon[,,"naturalstate.natveg"]
  SOCStock        <- dimSums(dimSums(SoilCarbon[,,"state",pmatch=TRUE], dim=3.3)* Landuse, dim=3.2)
  glo_SOCStock    <- dimSums(SOCStock, dim=1) 
  glo_SOCEmission <- (glo_SOCStock[,,"naturalstate"] - glo_SOCStock[,,"actualstate"])/1000
  if(r==1) plot(getYears(glo_SOCEmission, as.integer = TRUE),glo_SOCEmission, type="l", xlab="Time", ylab="Global SOC Debt in GtC", ylim=c(30,60))
  else     lines(getYears(glo_SOCEmission, as.integer = TRUE),glo_SOCEmission, type="l", xlab="Time", ylab="Global SOC Debt in GtC", col=col[r])
  range <- cbind(range,range(glo_SOCEmission))
}

litter_param <- collapseNames(read.magpie("/home/kristine/mnt/rd3mod/inputdata/sources/SOCbudgetParam/all.csv"))
litter_param <- mbind(litter_param, setNames(litter_param[,,"Default"],gsub("Default","Till",getNames(litter_param[,,"Default"]))))

print(cbind(rev, max=round(t(range)[,2],1), min=round(t(range)[,1],1), 
            lgc=as.array(litter_param[1,1,"lgc_ratio"][,,names(rev)]), 
            nc =as.array(litter_param[1,1,"nc_ratio"][,,names(rev)]), 
            colour=col))
```









