---
title: "First SOC budget analysis"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r load data}
library(moinput)
library(mrvalidation)
library(socbudget)

setConfig(cachefolder = "/home/kristine/WORK/R libraries/rd3mod_inputdata/cache/rev4.18.cellpanda/", forcecache = TRUE)
#setConfig(sourcefolder = "/home/kristine/mnt/rd3mod/inputdata/sources/")
setConfig(sourcefolder = "/home/kristine/WORK/R libraries/rd3mod_inputdata/sources/")

SoilCarbon <- calcOutput("CarbonBudget", aggregate = FALSE)
Landuse    <- calcOutput("Landuse",      aggregate=FALSE)

```

Calculate global carbon stocks

```{r Carbon Stock (cell iso reg glo)}

SOCStock     <- dimSums(dimSums(SoilCarbon, dim=3.2)* Landuse, dim=3)
glo_SOCStock <- dimSums(SOCStock, dim=1) 
cell2iso     <- toolGetMapping("CountryToCellMapping.csv", type = "cell")
iso_SOCStock <- toolCountryFill(toolAggregate(SOCStock, rel=cell2iso, from="celliso", to="iso", dim=1), fill=0)
iso2reg      <- toolMappingFile("regional",getConfig("regionmapping"),readcsv = TRUE)
reg_SOCStock <- toolAggregate(iso_SOCStock, rel=iso2reg, from="CountryCode", to="RegionCode")

```

Load validation data:

```{r Validation Stocks}

  LPJ_IPCC   <- calcOutput("ValidCarbonStocks", datasource = "LPJ_IPCC2006", aggregate="REG+GLO", try=TRUE)
  LPJ_rev21  <- calcOutput("ValidCarbonStocks", datasource = "LPJmL_rev21", aggregate="REG+GLO", try=TRUE)
  LPJ_car    <- calcOutput("ValidCarbonStocks", datasource = "LPJmLCarbon", aggregate="REG+GLO", try=TRUE)
  WISE       <- calcOutput("ValidCarbonStocks", datasource = "WISE", aggregate="REG+GLO", try=TRUE)
  GSOC       <- calcOutput("ValidCarbonStocks", datasource = "GSOC", aggregate="REG+GLO", try=TRUE)
  SoilGrids  <- calcOutput("ValidCarbonStocks", datasource = "SoilGrids", aggregate="REG+GLO", try=TRUE)
  
```

Plot global stocks

```{r plot glo stocks}

plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red", xlim=c(1951,2017),  ylim=c(400000,1300000))
lines(getYears(LPJ_IPCC, as.integer = TRUE), LPJ_IPCC["GLO",,1], type="l", col="green")
lines(getYears(LPJ_car, as.integer = TRUE), LPJ_car["GLO",,], type="l", col="darkgreen")
lines(getYears(LPJ_rev21, as.integer = TRUE), LPJ_rev21["GLO",,2], type="l", col="lightgreen")
lines(getYears(WISE, as.integer = TRUE), WISE["GLO",,], type="l", col="brown")
lines(getYears(SoilGrids, as.integer = TRUE), SoilGrids["GLO",,], type="l", col="blue")
lines(getYears(GSOC, as.integer = TRUE), GSOC["GLO",,], type="l", col="pink")
plot(c(getYears(glo_SOCStock, as.integer=TRUE)), glo_SOCStock, type="l", col="red")
```



Plot regional stocks

```{r plot reg stock, out.width="100%", out.height=1000}

library(mip)
library(quitte)
library(ggplot2)

getNames(reg_SOCStock) <- paste0("modeloutput.SOCbudget.", getNames(WISE,dim=3))
getSets(reg_SOCStock)  <- getSets(WISE) 

hist <- rbind(as.quitte(WISE["GLO",,,invert=TRUE]),
              as.quitte(GSOC["GLO",,,invert=TRUE]),
              as.quitte(SoilGrids["GLO",,,invert=TRUE]),
              as.quitte(LPJ_IPCC["GLO",,,invert=TRUE][,,1]),
              as.quitte(LPJ_car["GLO",,,invert=TRUE]),
              as.quitte(LPJ_rev21["GLO",,,invert=TRUE][,,2]))

mipLineHistorical(reg_SOCStock, hist, facet.ncol=4, scales="free_y")

```


```{r table dens climatezones}
    cell_GSOC      <- readSource("GSOC",  convert="onlycorrect")
    cell_WISE      <- readSource("WISE",  convert="onlycorrect")
    cell_SoilGrids <- readSource("SoilGrids",  convert="onlycorrect")
    
    koeppen     <- readSource("Koeppen", subtype="cellular", convert="onlycorrect" )
    getNames(koeppen) <- tolower(getNames(koeppen))
    koepp2IPCC  <- toolGetMapping("mapping_koeppen_ipcc.csv", type = "sectoral")
    koepp2IPCC$koeppen_geiger <- tolower(koepp2IPCC$koeppen_geiger)
    climateIPCC <- toolAggregate(koeppen, rel=koepp2IPCC, from="koeppen_geiger", to="ipcc_reduced", dim=3)
    climateIPCC <- climateIPCC[,getYears(SoilCarbon),]
  
    SOCDens_lut <- dimSums(SoilCarbon, dim=3.2) 
    SoilCshare  <- SOCDens_lut[,,"crop"]/collapseNames(SOCDens_lut[,,"natveg"])
    SoilCshare[is.na(SoilCshare)]       <- 1
    SoilCshare[is.infinite(SoilCshare)] <- 1
    
    SoilCshare_ipcczone <- dimSums(climateIPCC * SoilCshare * Landuse[,,"crop"], dim=1)/dimSums(climateIPCC * Landuse[,,"crop"], dim=1)
    print(SoilCshare_ipcczone)
    
    
```


```{r plot density maps}

cropland_share <- dimSums(SoilCarbon[,,"crop"], dim=3)/dimSums(SoilCarbon[,,"natveg"], dim=3)

luplot::plotmap(cropland_share[,"y2000",])


```

