---
title: "Global SOC scenarios"
output:
  md_document:
    variant: markdown_github
  html_document:  
---

```{r load}
library(mrcommons)
library(mrvalidation)
library(mrSOCbudget)
library(magpiesets)

rev <- "rev0.77init_lu"

setConfig(cachefolder  = paste0("/home/kristine/mnt/rd3mod/inputdata/cache/", rev), forcecache = TRUE)
setConfig(sourcefolder = "/home/kristine/mnt/rd3mod/inputdata/sources/")
setConfig(outputfolder = "/home/kristine/mnt/rd3mod/inputdata/output/")

revisions   <- c(InitLu="rev0.77init_lu", InitNv="rev0.77init_natveg", InitMix="rev0.77init_mixed")
filesNeeded <- c("SoilCarbon.rds","Landuse.rds")


# for(item in revisions){
#    dir.create(path=paste0("Data/",names(which(revisions[]==item))))
#    untar(paste0(getConfig("outputfolder"),"/",item, "_h12_carbonbudget.tgz"), files=filesNeeded, exdir=paste0("Data/", names(which(revisions[]==item))))#, extras="--keep-newer-files ")
# }

outputdir <- "Output/Images"

```

Calc global numbers

```{r Carbon Emissions (glo)}

library(ggplot2)

glo_SOCStock <- NULL

for(r in 1:length(revisions)){
  SoilCarbon <- read.magpie(paste0("Data/",names(revisions[r]),"/SoilCarbon.rds"))
  Landuse    <- read.magpie(paste0("Data/",names(revisions[r]),"/Landuse.rds"))
  SoilCarbon[,,"naturalstate.crop"] <- SoilCarbon[,,"naturalstate.natveg"]
  SOCStock        <- toolConditionalReplace(dimSums(dimSums(SoilCarbon[,,"state",pmatch=TRUE], dim=3.3)* Landuse, dim=3.2), "is.nan()",0)
  glo_SOCStock    <- mbind(glo_SOCStock, add_dimension(dimSums(SOCStock, dim=1), dim=3.1, nm=names(revisions[r]), add="scenario")) 
}

# 
```

```{r plot Carbon Emissions (glo)}

plot_rev <- c(2,3)

names(revisions) <- c("steady state of land use","steady state of potential natural vegetation","mean of steady states above")



colr <- c("black","green","red","brown","pink","darkgreen","yellow","blue")
glo_SOCEmission <- collapseNames(glo_SOCStock[,,"naturalstate"] - glo_SOCStock[,,"actualstate"])/1000
glo_SOCShare    <- collapseNames( toolConditionalReplace(glo_SOCStock[,,"actualstate"]/glo_SOCStock[,,"naturalstate"], "is.na()",0) )

getNames(glo_SOCEmission) <- names(revisions)
plot(getYears( glo_SOCEmission, as.integer = TRUE), -glo_SOCEmission[,,1], type="l", xlab="Time", ylab="Global SOC gap in GtC", ylim=c(-45,-35))
legend("topleft", legend=names(revisions[c(1,plot_rev)]), col=colr[c(1,plot_rev)], lty=1, cex=0.8)
for(r in plot_rev) lines(getYears(glo_SOCEmission, as.integer = TRUE), -glo_SOCEmission[,,names(revisions[r])], type="l", col=colr[r])
print(cbind(colr[c(1,plot_rev)], names(revisions[c(1,plot_rev)])))
print(glo_SOCStock[,,"actualstate"])

#plot(getYears( glo_SOCEmission, as.integer = TRUE), dimSums(Landuse[,,"crop"], dim=1), type="l")
#plot(getYears( glo_SOCEmission, as.integer = TRUE), dimSums(glo_SOCStock[,,"Baseline.actualstate"], dim=1), type="l")


```


```{r ggplot}

theme_set(theme_bw())
legend_size <- 10

SOCemis <- ggplot() + geom_line(data= as.data.frame(-glo_SOCEmission[,seq(1975,2010,1),c(1,plot_rev)]),  aes(x = Year, y = Value, group=Data1, color=Data1)) +
  labs( x = "Year", 
        y = "Global SOC gap in GtC",
        color="Initilization of SOC stocks in 1960 by") +
  scale_x_discrete(breaks=seq(1975,2010,5)) +
  scale_y_continuous(limits = c(-45,-0),
                     breaks = seq(-45,0,5)) +
  theme(rect=element_blank(),
        axis.title.y= element_text(size=legend_size, margin = margin(t = 0, r = 10, b = 0, l = 0, unit = "pt")),
        axis.title.x= element_text(size=legend_size, margin = margin(t = 10, r = 0, b = 0, l = 0, unit = "pt")),
        axis.text.x = element_text(angle=60, hjust=0.8, vjust=0.8, size=legend_size))

SOCemis

ggsave(paste0(outputdir,"/scenario_lu.png"), plot=SOCemis)

```



