---
  title: "First SOC budget flow analysis"
output:
  html_document:
  df_print: paged
pdf_document: default
---

```{r load}
library(mrcommons)
library(mrvalidation)
library(mrsoil)
library(magpiesets)

rev <- "rev0.78baseline"

outputdir <- "Output/Images"

setConfig(cachefolder  = paste0("/home/kristine/mnt/rd3mod/inputdata/cache/", rev), forcecache = TRUE)
setConfig(sourcefolder = "/home/kristine/mnt/rd3mod/inputdata/sources/")
setConfig(outputfolder = "/home/kristine/mnt/rd3mod/inputdata/output/")
untar(paste0(getConfig("outputfolder"),"/",rev, "_h12_carbonbudget.tgz"), exdir="Data/Baseline", extras="--keep-newer-files ")

revfolder <- "Data/Baseline/"

```

```{r load data}

files <- list.files("Data")

CarbonInput      <- readRDS(paste0(revfolder,"CarbonInput.rds"))
CarbonLitter     <- readRDS(paste0(revfolder,"CarbonLitter.rds"))
CarbonManure     <- readRDS(paste0(revfolder,"CarbonManure.rds"))          
CarbonResidues   <- readRDS(paste0(revfolder,"CarbonResidues.rds"))
CarbonHarvest    <- readRDS(paste0(revfolder,"Crop_Harvest.rds"))
SoilCarbonOut    <- readRDS(paste0(revfolder,"SoilCarbon.rds"))

Landuse          <- readRDS(paste0(revfolder,"Landuse.rds"))
LanduseChange    <- readRDS(paste0(revfolder,"LanduseChange.rds"))

FAOmassbalance   <- readRDS(paste0(revfolder,"FAOmassbalance_ISO.rds"))
ManureExcreted   <- readRDS(paste0(revfolder,"Manure_excreted.rds"))
ManureRecycled   <- readRDS(paste0(revfolder,"Manure_recycled.rds"))
ResidueBiomass   <- readRDS(paste0(revfolder,"Residue_Biomass.rds"))
ResiduesAgDemand <- readRDS(paste0(revfolder,"ResiduesAg_FieldBalance.rds"))

```

```{r globals}
grepSpaceTime     <- function(x){return(dimSums(x[,"y2010","c"],dim=1))}


#Agriculture
kcr        <- findset("kcr")
kli        <- findset("kli")
kres       <- findset("kres")
kExResPast <- setdiff(findset("kall"),c(kres,kli,"pasture","wood","woodfuel","scp","fish"))
kPrim      <- setdiff(findset("kall"),c(kli,"scp","fish")) 

CropHANPP         <- dimSums(grepSpaceTime(FAOmassbalance[,,kcr][,,c("food","waste","other_util","bioenergy","feed",
                                                                     "milling","refining","extracting","fermentation","distilling")]), dim=3)
CropFEED          <- grepSpaceTime(dimSums(FAOmassbalance[,,kExResPast][,,"feed"], dim=3.1))
CropPRIM          <- CropHANPP-CropFEED
ResFEED           <- grepSpaceTime(dimSums(FAOmassbalance[,,kres][,,"feed"], dim=3.1))
ResPRIM           <- dimSums(grepSpaceTime(FAOmassbalance[,,kres][,,c("other_util","bioenergy")]), dim=3)


FEED              <- grepSpaceTime(dimSums(FAOmassbalance[,,kPrim][,,"feed"], dim=3.1))
LivstHANPP        <- dimSums(grepSpaceTime(FAOmassbalance[,,kli][,,c("food","waste","other_util")]), dim=3)
LivstCropHANPP    <- (CropFEED+ResFEED)/FEED * LivstHANPP

ResidueBiomassTot <- grepSpaceTime(dimSums(ResidueBiomass, dim=3.2))
ResidueRecycledTot<- grepSpaceTime(dimSums(ResiduesAgDemand[,,"recycle"], dim=3.2))

ManureExcretedTot <- grepSpaceTime(dimSums(ManureExcreted[,,c("stubble_grazing","confinement")], dim=c(3.1,3.2)))
ManureRecycledTot <- grepSpaceTime(dimSums(ManureRecycled, dim=3.1))

#Soil

### Carbon To
CarbonTo            <- dimSums(toolConditionalReplace(SoilCarbonOut[,"y2010","carbontransfer"], "<0", 0),dim=c(1,3.3))
CarbonToEff         <- dimSums(SoilCarbonOut[,"y2010","carbontransfer"], dim=c(1,3.3))
CarbonToPools       <- dimSums(toolConditionalReplace(SoilCarbonOut[,"y2010","carbontransfer"], "<0", 0),dim=c(1))

####### delete when new output on decay is ready
# Decay

ActiveDecay        <- mbind(setNames(calcOutput("ActiveDecay",  landtype="crop",   aggregate = FALSE),"crop"),
                              setNames(calcOutput("ActiveDecay",  landtype="natveg", aggregate = FALSE),"natveg"))
SlowDecay          <- mbind(setNames(calcOutput("SlowDecay",  landtype="crop",   aggregate = FALSE),"crop"),
                              setNames(calcOutput("SlowDecay",  landtype="natveg", aggregate = FALSE),"natveg"))
PassiveDecay       <- mbind(setNames(calcOutput("PassiveDecay", landtype="crop",   aggregate = FALSE),"crop"),
                              setNames(calcOutput("PassiveDecay", landtype="natveg", aggregate = FALSE),"natveg"))
decay <- calcOutput("Decay", aggregate = FALSE)
subpools     <- c("active","slow","passive")
names        <- as.vector(outer(getNames(Landuse), subpools, paste, sep="."))
Decay <- new.magpie(getCells(Landuse), getYears(Landuse), names, fill = 0)

Decay[,,"active"]                  <- ActiveDecay
Decay[,,"slow"]                    <- SlowDecay
Decay[,,"passive"]                 <- PassiveDecay

rm(ActiveDecay, SlowDecay, PassiveDecay)

#
####### end delete

DecayCut          <- Decay
DecayCut[Decay>1] <- 1 

### Carbon In
f1        <- param[,,"f1"]
f2_crop   <- param[,,"f2_ft"]
f2_natveg <- param[,,"f2_nt"]
f3        <- param[,,"f3"]

# f2 has to be updated with new test runs

MineralizeFracInput <- setCells(mbind(add_dimension(collapseNames(CarbonInput[,,"totalC",invert=TRUE][1,,"res"]), dim=3.1, add = "lu", nm = "crop"),
                                      add_dimension(collapseNames(CarbonInput[,,"totalC",invert=TRUE][1,,"res"]), dim=3.1, add = "lu", nm = "natveg")), "GLO")
MineralizeFracInput[,,"metabDOC"]        <- f1
MineralizeFracInput[,,"crop.strucDOC"]   <- f2_crop
MineralizeFracInput[,,"natveg.strucDOC"] <- f2_natveg
MineralizeFracInput[,,"ligninC"]         <- f3

input2lu <- as.data.frame(list(c("res", findset("kli"), "litfall"),
                            c(rep("crop",6), "natveg")), col.names=c("input","lu"))


CarbonInEff       <- collapseNames(dimSums(toolAggregate(CarbonInput[,"y2010",][,,"totalC",invert=TRUE], rel=input2lu, dim=3.1) *
                                            MineralizeFracInput[,"y2010",] * Landuse[,"y2010",], dim=c(1,3.2)))

CarbonInSource   <- collapseNames(dimSums(CarbonInput[,"y2010",][,,"totalC",invert=TRUE]  * 
                                            toolAggregate(MineralizeFracInput[,"y2010",] * Landuse[,"y2010",], rel=input2lu, from="lu", to="input", dim=3.1), dim=c(1,3.2)))

CarbonInRaw       <- collapseNames(dimSums(SoilCarbonOut[,"y2010","steadystate"]*DecayCut[,"y2010",]*Landuse[,"y2010",], dim=c(1,3.3)))

### Carbon Out

CarbonOutRaw      <- collapseNames(dimSums(SoilCarbonOut[,"y2010","interstate"]*DecayCut[,"y2010",]*Landuse[,"y2010",], dim=c(1,3.3)))
CarbonOutEff      <- CarbonOutRaw + CarbonInEff - CarbonInRaw



### SOC State

SOCstate <- dimSums(SoilCarbonOut[,c("y2009","y2010"),c("actualstate","interstate")]*Landuse[,c("y2009","y2010"),], dim=c(1,3.3))

```


```{r residues}

### Residues
  # originally from moinput
  ResidueDemand       <- dimSums(collapseNames(calcOutput("ResFieldBalancePast", cellular=TRUE, products = "kres", aggregate = FALSE)[,,"c"]), dim=1)
  ResidueRecyclingAg  <- ResidueDemand[,,"recycle"]
  ResidueRecyclingBg  <- dimSums(calcOutput("ResBiomass", cellular=TRUE, aggregate = FALSE)[,,"bg"][,,c("c")], dim=c(1,3))
  ResiduesMoinput     <- dimSums(ResidueRecyclingAg, dim=3) + ResidueRecyclingBg
  
  # Residues with cut of overflow
  ResiduesDensities   <- calcOutput("CarbonResidues", aggregate=FALSE)[,,"c"]
  Landuse             <- calcOutput("Landuse", aggregate=FALSE)
  ResiduesSOCbudget   <- dimSums(Landuse[,getYears(ResiduesDensities),"crop"]*ResiduesDensities, dim=c(1,3))

  print(mbind(ResiduesMoinput, ResiduesSOCbudget, ResiduesSOCbudget/ResiduesMoinput))

  # Corrected Residues shares for different plant parts  
  RatioPlantParts     <- mbind(ResidueRecyclingAg, setNames(ResidueRecyclingBg, "res_roots"))/(dimSums(ResidueRecyclingAg, dim=3)+ResidueRecyclingBg)
  
  ResiduesCorrected   <- collapseNames(RatioPlantParts * ResiduesSOCbudget)
  
  # total residues and residue demands
  
  ResidueBg     <- ResidueRecyclingBg
  ResidueAg     <- dimSums(calcOutput("ResBiomass", cellular=TRUE, aggregate = FALSE)[,,"ag"][,,c("c")], dim=c(1,3))
  ResidueTotal  <- ResidueAg + ResidueBg 
  
```
  
Quite a lot of residues get lost, due to cutting extreme values in the later years.
Cutting algorithm, cuts everything bigger the 95%-percentile.
How we deal with that? 
* Should we do a yearly extrem value cutting?
* Should we investigate that deeper?
* Should we leave it like this?



```{r manure}

### Manure
  # originally from moinput
  ManureApplication   <- calcOutput("ManureRecyclingCroplandPast", products = "kli", cellular = TRUE, aggregate = FALSE)[,,"c"]
  ManureGrazing       <- calcOutput("Excretion", cellular = TRUE, attributes = "npkc", aggregate = FALSE)[,,"stubble_grazing"][,,"c"]
  ManureMoinput       <- collapseNames(dimSums(ManureApplication, dim=1) + dimSums(ManureGrazing, dim=1))
 
  # Manure with cut of overflow
  ManureDensities     <- calcOutput("CarbonManure", aggregate=FALSE)[,,"c"]
  Landuse             <- calcOutput("Landuse", aggregate=FALSE)
  ManureSOCbudget     <- dimSums(Landuse[,getYears(ManureDensities),"crop"]*ManureDensities, dim=1)
 
  print(mbind(dimSums(ManureMoinput, dim=3), dimSums(ManureSOCbudget, dim=3), dimSums(ManureSOCbudget, dim=3)/dimSums(ManureMoinput, dim=3)))
  
  ManureCorrected     <- ManureSOCbudget
  
  ManureExcreted      <- dimSums(calcOutput("Excretion", cellular = TRUE, attributes = "npkc", aggregate = FALSE)[,,"c"][,,c("confinement","stubble_grazing")], dim=c(1,3.3))
  
  print(mbind(dimSums(ManureExcreted, dim=3), dimSums(ManureMoinput, dim=3), dimSums(ManureCorrected, dim=3)))
  print(quantile(ManureApplication+ManureGrazing, probs=seq(0,1,0.02)))
  range(ManureApplication+ManureGrazing)
```
  
Same problem here. Manure share is going down.




```{r production}

#Production     <- collapseNames(calcOutput("Production", products="kcr", cellular=TRUE, attributes="dm", irrigation=FALSE, aggregate = FALSE))
Balance        <- calcOutput("FAOmassbalance", aggregate=FALSE)

CropProduction <- dimSums(Balance[,,findset("kcr")][,,"production"][,,"c"], dim=c(1,3))
FeedProduction <- dimSums(Balance[,,c("pasture",findset("kap"),findset("kres"),"scp"), invert=TRUE][,,"feed"][,,"c"], dim=c(1,3))
ResidueFeed    <- dimSums(Balance[,,findset("kres")][,,"feed"][,,"c"], dim=c(1,3))

print(mbind(CropProduction,FeedProduction,ResidueFeed))
```



